services:
  mxlrc:
    container_name: mxlrc
    build: .
    platform: linux/arm64
    # Restart policy: 'no' means the container will not restart after the script finishes.
    # Ideal for a task that runs only once.
    restart: 'no'

    # --- Volumes ---
    # This is where your local music directory is "mounted" into the container.
    # Adjust the path on the left to your actual path.
    # The path on the right is the path inside the container.
    volumes:
      - /media/pi/Harddrive/Music:/music

    # --- Environment variables ---
    # This is where the container is configured. These values are read by the entrypoint.sh script.
    environment:
      # Your personal Musixmatch token
      - MX_TOKEN=<Musixmatch-TOKEN>

      # The directory inside the container to be scanned.
      # Must match the target path in the "volumes" section.
      - MUSIC_DIR=/music

      # Time in seconds to wait between individual downloads.
      - SLEEP_TIME=15

      # Set to "true" to overwrite existing .lrc files.
      # Otherwise, set to "false".
      - UPDATE_FILES=false
