# docker-compose.yml für den mxlrc-Downloader

# Version der Docker-Compose-Syntax
version: '3.8'

services:
  # Name des Services
  mxlrc-downloader:
    # Anweisung, das Image aus dem Dockerfile im aktuellen Verzeichnis zu bauen
    build: .
    # WICHTIG: Definiert die Zielplattform. Unbedingt für den Raspberry Pi 5 erforderlich!
    platform: linux/arm64
    # Neustart-Politik: 'no' bedeutet, dass der Container nach Beendigung des Skripts nicht neu startet.
    # Ideal für eine Aufgabe, die nur einmal ausgeführt wird.
    restart: 'no'

    # --- Volumes ---
    # Hier wird Ihr lokales Musikverzeichnis in den Container "eingehängt".
    # Passen Sie den Pfad auf der linken Seite an Ihren tatsächlichen Pfad an.
    # Der Pfad auf der rechten Seite ist der Pfad innerhalb des Containers.
    volumes:
      - /media/pi/Toshiba/Musik/Rap/Interpreten:/music

    # --- Umgebungsvariablen ---
    # Hier wird der Container konfiguriert. Diese Werte werden vom entrypoint.sh-Skript gelesen.
    environment:
      # Ihr persönlicher Musixmatch-Token
      - MX_TOKEN=25070582c4feea509a78235159f7d50a59d80fb4b02645607c826f

      # Das Verzeichnis im Container, das durchsucht werden soll.
      # Muss mit dem Zielpfad im "volumes"-Abschnitt übereinstimmen.
      - MUSIC_DIR=/music

      # Zeit in Sekunden, die zwischen den einzelnen Downloads gewartet wird.
      - SLEEP_TIME=15

      # Auf "true" setzen, um bereits vorhandene .lrc-Dateien zu überschreiben.
      # Andernfalls auf "false" setzen.
      - UPDATE_FILES=true
