services:
  mxlrc:
    container_name: mxlrc
    image: ghcr.io/m4rc-xx/mxlrc:latest
    restart: 'no'

    # --- Volumes ---
    # This is where the user's local music directory is "mounted" into the container.
    # The user needs to adjust the path on the left to their actual path.
    volumes:
      - /media/pi/Harddrive/Music::/music # Example: Mounts a 'music' folder from the current directory

    environment:
      # The user's personal Musixmatch token
      - MX_TOKEN= #Musixmatch Usertoken

      # The directory inside the container to be scanned.
      # Must match the target path in the "volumes" section.
      - MUSIC_DIR=/music

      # Time in seconds to wait between individual downloads.
      - SLEEP_TIME=15

      # Set to "true" to overwrite existing .lrc files.
      # Otherwise, set to "false".
      - UPDATE_FILES=false
